-- ============================================================
-- Migration: Add Missing Tables & Storage Buckets
-- Date: 2026-05-20
-- Description: Adds tables missing from initial schema:
--   kontak_sekolah, ekstrakurikuler, kegiatan_harian,
--   laporan_perkembangan, pesan_masuk, statistik_utama
--   + Storage bucket definitions
-- ============================================================

-- -----------------------------------------------
-- 1. KONTAK SEKOLAH
-- -----------------------------------------------
CREATE TABLE public.kontak_sekolah (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alamat  TEXT NOT NULL,
  whatsapp TEXT NOT NULL,
  email_utama TEXT NOT NULL,
  email_admin TEXT NOT NULL,
  jam_operasional TEXT NOT NULL,
  maps_embed_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- -----------------------------------------------
-- 2. EKSTRAKURIKULER
-- -----------------------------------------------
CREATE TABLE public.ekstrakurikuler (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_eskul TEXT NOT NULL,
  deskripsi  TEXT,
  jadwal     TEXT,
  image_url  TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- -----------------------------------------------
-- 3. KEGIATAN HARIAN
-- -----------------------------------------------
CREATE TABLE public.kegiatan_harian (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  waktu_mulai   TEXT NOT NULL,
  waktu_selesai TEXT NOT NULL,
  nama_kegiatan TEXT NOT NULL,
  deskripsi     TEXT,
  icon_svg      TEXT,
  urutan        INTEGER NOT NULL DEFAULT 0,
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- -----------------------------------------------
-- 4. LAPORAN PERKEMBANGAN
-- -----------------------------------------------
CREATE TABLE public.laporan_perkembangan (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  siswa_id         UUID NOT NULL REFERENCES public.siswa(id) ON DELETE CASCADE,
  semester         TEXT NOT NULL,
  tahun_ajaran     TEXT NOT NULL,
  catatan_guru     TEXT,
  dokumen_rapor_url TEXT,
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- -----------------------------------------------
-- 5. PESAN MASUK
-- -----------------------------------------------
CREATE TABLE public.pesan_masuk (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_pengirim  TEXT NOT NULL,
  email_pengirim TEXT NOT NULL,
  telepon        TEXT,
  subjek         TEXT,
  isi_pesan      TEXT NOT NULL,
  status         TEXT NOT NULL DEFAULT 'belum_dibaca',
  created_at     TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at     TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- -----------------------------------------------
-- 6. STATISTIK UTAMA
-- -----------------------------------------------
CREATE TABLE public.statistik_utama (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kunci     TEXT NOT NULL UNIQUE,
  nilai     TEXT NOT NULL,
  deskripsi TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.kontak_sekolah ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ekstrakurikuler ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kegiatan_harian ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.laporan_perkembangan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pesan_masuk ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.statistik_utama ENABLE ROW LEVEL SECURITY;

-- kontak_sekolah: public read, authenticated write
CREATE POLICY "Public read kontak_sekolah" ON public.kontak_sekolah FOR SELECT USING (true);
CREATE POLICY "Authenticated insert kontak_sekolah" ON public.kontak_sekolah FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated update kontak_sekolah" ON public.kontak_sekolah FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated delete kontak_sekolah" ON public.kontak_sekolah FOR DELETE USING (auth.role() = 'authenticated');

-- ekstrakurikuler: public read, authenticated write
CREATE POLICY "Public read ekstrakurikuler" ON public.ekstrakurikuler FOR SELECT USING (true);
CREATE POLICY "Authenticated insert ekstrakurikuler" ON public.ekstrakurikuler FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated update ekstrakurikuler" ON public.ekstrakurikuler FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated delete ekstrakurikuler" ON public.ekstrakurikuler FOR DELETE USING (auth.role() = 'authenticated');

-- kegiatan_harian: public read, authenticated write
CREATE POLICY "Public read kegiatan_harian" ON public.kegiatan_harian FOR SELECT USING (true);
CREATE POLICY "Authenticated insert kegiatan_harian" ON public.kegiatan_harian FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated update kegiatan_harian" ON public.kegiatan_harian FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated delete kegiatan_harian" ON public.kegiatan_harian FOR DELETE USING (auth.role() = 'authenticated');

-- laporan_perkembangan: authenticated only (sensitive student data)
CREATE POLICY "Authenticated read laporan_perkembangan" ON public.laporan_perkembangan FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated insert laporan_perkembangan" ON public.laporan_perkembangan FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated update laporan_perkembangan" ON public.laporan_perkembangan FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated delete laporan_perkembangan" ON public.laporan_perkembangan FOR DELETE USING (auth.role() = 'authenticated');

-- pesan_masuk: siapapun bisa insert (form kontak publik), authenticated bisa baca/update/delete
CREATE POLICY "Public insert pesan_masuk" ON public.pesan_masuk FOR INSERT WITH CHECK (true);
CREATE POLICY "Authenticated read pesan_masuk" ON public.pesan_masuk FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated update pesan_masuk" ON public.pesan_masuk FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated delete pesan_masuk" ON public.pesan_masuk FOR DELETE USING (auth.role() = 'authenticated');

-- statistik_utama: public read, authenticated write
CREATE POLICY "Public read statistik_utama" ON public.statistik_utama FOR SELECT USING (true);
CREATE POLICY "Authenticated insert statistik_utama" ON public.statistik_utama FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated update statistik_utama" ON public.statistik_utama FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated delete statistik_utama" ON public.statistik_utama FOR DELETE USING (auth.role() = 'authenticated');

-- ============================================================
-- STORAGE BUCKETS
-- ============================================================

-- dokumen-pendukung: dokumen pendukung pendaftar (privat)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'dokumen-pendukung',
  'dokumen-pendukung',
  false,
  10485760, -- 10 MB
  ARRAY['application/pdf', 'image/jpeg', 'image/png', 'image/webp']
) ON CONFLICT (id) DO NOTHING;

-- dokumen-pribadi: dokumen pribadi siswa (privat)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'dokumen-pribadi',
  'dokumen-pribadi',
  false,
  10485760, -- 10 MB
  ARRAY['application/pdf', 'image/jpeg', 'image/png', 'image/webp']
) ON CONFLICT (id) DO NOTHING;

-- dokumen-rapor: file PDF rapor siswa (privat)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'dokumen-rapor',
  'dokumen-rapor',
  false,
  20971520, -- 20 MB
  ARRAY['application/pdf']
) ON CONFLICT (id) DO NOTHING;

-- dokumentasi-prestasi: foto dokumentasi prestasi (publik)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'dokumentasi-prestasi',
  'dokumentasi-prestasi',
  true,
  5242880, -- 5 MB
  ARRAY['image/jpeg', 'image/png', 'image/webp']
) ON CONFLICT (id) DO NOTHING;

-- konten-publik: gambar berita, galeri, dll (publik)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'konten-publik',
  'konten-publik',
  true,
  5242880, -- 5 MB
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']
) ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- STORAGE RLS POLICIES
-- ============================================================

-- konten-publik: siapapun bisa baca, hanya authenticated yg bisa upload/delete
CREATE POLICY "Public read konten-publik"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'konten-publik');

CREATE POLICY "Authenticated upload konten-publik"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'konten-publik' AND auth.role() = 'authenticated');

CREATE POLICY "Authenticated delete konten-publik"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'konten-publik' AND auth.role() = 'authenticated');

-- dokumentasi-prestasi: publik read, authenticated write
CREATE POLICY "Public read dokumentasi-prestasi"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'dokumentasi-prestasi');

CREATE POLICY "Authenticated upload dokumentasi-prestasi"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'dokumentasi-prestasi' AND auth.role() = 'authenticated');

CREATE POLICY "Authenticated delete dokumentasi-prestasi"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'dokumentasi-prestasi' AND auth.role() = 'authenticated');

-- dokumen-rapor: privat, hanya authenticated
CREATE POLICY "Authenticated access dokumen-rapor"
  ON storage.objects FOR ALL
  USING (bucket_id = 'dokumen-rapor' AND auth.role() = 'authenticated')
  WITH CHECK (bucket_id = 'dokumen-rapor' AND auth.role() = 'authenticated');

-- dokumen-pendukung: privat, hanya authenticated
CREATE POLICY "Authenticated access dokumen-pendukung"
  ON storage.objects FOR ALL
  USING (bucket_id = 'dokumen-pendukung' AND auth.role() = 'authenticated')
  WITH CHECK (bucket_id = 'dokumen-pendukung' AND auth.role() = 'authenticated');

-- dokumen-pribadi: privat, hanya authenticated
CREATE POLICY "Authenticated access dokumen-pribadi"
  ON storage.objects FOR ALL
  USING (bucket_id = 'dokumen-pribadi' AND auth.role() = 'authenticated')
  WITH CHECK (bucket_id = 'dokumen-pribadi' AND auth.role() = 'authenticated');

-- ============================================================
-- SEED DATA AWAL
-- ============================================================

-- Kontak sekolah default (satu baris, diupdate via admin)
INSERT INTO public.kontak_sekolah (alamat, whatsapp, email_utama, email_admin, jam_operasional)
VALUES (
  'Jl. Raya Dimoro, Kec. Dimoro, Kab. XYZ',
  '0818-0000-0000',
  'info@mimpkdimoro.sch.id',
  'admin@mimpkdimoro.sch.id',
  E'Senin - Kamis: 07.30 - 11.30 WIB\nJumat: 07.30 - 11.00 WIB'
) ON CONFLICT DO NOTHING;

-- Statistik utama default
INSERT INTO public.statistik_utama (kunci, nilai, deskripsi)
VALUES
  ('jumlah_siswa', '0', 'Total siswa aktif'),
  ('jumlah_guru', '0', 'Total tenaga pengajar'),
  ('tahun_berdiri', '2000', 'Tahun sekolah berdiri'),
  ('akreditasi', 'A', 'Nilai akreditasi sekolah')
ON CONFLICT (kunci) DO NOTHING;
