-- Create Profiles Table
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'orang_tua',
  nama_lengkap TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Pendaftar Table
CREATE TABLE public.pendaftar (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  email TEXT,
  nama_lengkap TEXT NOT NULL,
  nama_panggilan TEXT,
  jenis_kelamin TEXT,
  tempat_lahir TEXT,
  tanggal_lahir DATE,
  agama TEXT,
  kewarganegaraan TEXT,
  anak_ke INTEGER,
  jumlah_saudara_kandung INTEGER,
  status_anak TEXT,
  bahasa_sehari_hari TEXT,
  berat_badan INTEGER,
  tinggi_badan INTEGER,
  golongan_darah TEXT,
  cita_cita TEXT,
  alamat_lengkap TEXT,
  nomor_telepon TEXT,
  jarak_tempat_tinggal TEXT,
  nama_ayah_kandung TEXT,
  pendidikan_ayah TEXT,
  pekerjaan_ayah TEXT,
  nama_ibu_kandung TEXT,
  pendidikan_ibu TEXT,
  pekerjaan_ibu TEXT,
  wali_nama TEXT,
  wali_pendidikan TEXT,
  wali_hubungan TEXT,
  wali_pekerjaan TEXT,
  memiliki_kebutuhan_khusus BOOLEAN DEFAULT false,
  jenis_kebutuhan_khusus JSONB,
  deskripsi_kebutuhan_khusus TEXT,
  dokumen_pendukung_url TEXT,
  jalur_pendaftaran TEXT DEFAULT 'Online',
  status_pendaftaran TEXT DEFAULT 'Menunggu Konfirmasi',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Siswa Table
CREATE TABLE public.siswa (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  nama_lengkap TEXT NOT NULL,
  tanggal_lahir DATE,
  kelompok TEXT,
  pendaftar_asli_id UUID REFERENCES public.pendaftar(id) ON DELETE SET NULL,
  profile_orang_tua_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Testimoni Table
CREATE TABLE public.testimoni (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_orang_tua TEXT NOT NULL,
  status_orang_tua TEXT,
  isi_testimoni TEXT NOT NULL,
  is_featured BOOLEAN DEFAULT false,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Kalender Akademik Table
CREATE TABLE public.kalender_akademik (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  judul TEXT NOT NULL,
  tanggal DATE NOT NULL,
  tanggal_berakhir DATE,
  waktu TEXT,
  kategori TEXT,
  deskripsi TEXT,
  warna TEXT DEFAULT '#3b82f6',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Biaya Pendaftaran Table
CREATE TABLE public.biaya_pendaftaran (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  komponen_biaya TEXT NOT NULL,
  biaya_putra INTEGER NOT NULL,
  biaya_putri INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Prestasi Table
CREATE TABLE public.prestasi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tahun INTEGER NOT NULL,
  nama_prestasi TEXT NOT NULL,
  tingkat TEXT NOT NULL,
  deskripsi TEXT,
  nama_siswa TEXT NOT NULL,
  dokumentasi_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Konten Halaman Table
CREATE TABLE public.konten_halaman (
  slug TEXT PRIMARY KEY,
  judul TEXT NOT NULL,
  isi TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Berita Table
CREATE TABLE public.berita (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  judul TEXT NOT NULL,
  ringkasan TEXT,
  isi_lengkap TEXT NOT NULL,
  image_url TEXT,
  penulis_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'draft',
  tanggal_terbit DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Galeri Table
CREATE TABLE public.galeri (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keterangan TEXT,
  kategori TEXT,
  image_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- SETTING UP RLS (Row Level Security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pendaftar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.siswa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimoni ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kalender_akademik ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.biaya_pendaftaran ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prestasi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.konten_halaman ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.berita ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.galeri ENABLE ROW LEVEL SECURITY;

-- Untuk tahap development/migrasi awal, ini adalah fallback policy agar bisa read, insert, update dari Anon Key
CREATE POLICY "Enable read access for all users" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Enable all access for all users" ON public.profiles FOR ALL USING (true);

CREATE POLICY "Enable read access for all users" ON public.pendaftar FOR SELECT USING (true);
CREATE POLICY "Enable all access for all users" ON public.pendaftar FOR ALL USING (true);

CREATE POLICY "Enable read access for all users" ON public.siswa FOR SELECT USING (true);
CREATE POLICY "Enable all access for all users" ON public.siswa FOR ALL USING (true);

CREATE POLICY "Enable read access for all users" ON public.testimoni FOR SELECT USING (true);
CREATE POLICY "Enable all access for all users" ON public.testimoni FOR ALL USING (true);

CREATE POLICY "Enable read access for all users" ON public.kalender_akademik FOR SELECT USING (true);
CREATE POLICY "Enable all access for all users" ON public.kalender_akademik FOR ALL USING (true);

CREATE POLICY "Enable read access for all users" ON public.biaya_pendaftaran FOR SELECT USING (true);
CREATE POLICY "Enable all access for all users" ON public.biaya_pendaftaran FOR ALL USING (true);

CREATE POLICY "Enable read access for all users" ON public.prestasi FOR SELECT USING (true);
CREATE POLICY "Enable all access for all users" ON public.prestasi FOR ALL USING (true);

CREATE POLICY "Enable read access for all users" ON public.konten_halaman FOR SELECT USING (true);
CREATE POLICY "Enable all access for all users" ON public.konten_halaman FOR ALL USING (true);

CREATE POLICY "Enable read access for all users" ON public.berita FOR SELECT USING (true);
CREATE POLICY "Enable all access for all users" ON public.berita FOR ALL USING (true);

CREATE POLICY "Enable read access for all users" ON public.galeri FOR SELECT USING (true);
CREATE POLICY "Enable all access for all users" ON public.galeri FOR ALL USING (true);
